### Setup inicial

In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

_2009_path = '2009/DADOS/'

dm_ies_path = 'DM_IES.CSV'
dm_curso_path = 'DM_CURSO.CSV'
dm_docente_path = 'DM_DOCENTE.CSV'
dm_aluno_path = 'DM_ALUNO.CSV'
dm_unidade_funcionamento_path = 'DM_UNIDADE_FUNCIONAMENTO.CSV'
dm_vagas_ead_path = 'DM_VAGAS_INSCRITOS_EAD.CSV'

In [9]:
# Ler arquivos

encoding='ISO-8859-1'

dm_ies = pd.read_csv(filepath_or_buffer=_2009_path + dm_ies_path, sep='|', encoding=encoding)
dm_curso = pd.read_csv(filepath_or_buffer=_2009_path + dm_curso_path, sep='|', encoding='ISO-8859-1')
dm_docente = pd.read_csv(filepath_or_buffer=_2009_path + dm_docente_path, sep='|', encoding='ISO-8859-1')
dm_aluno = pd.read_csv(filepath_or_buffer=_2009_path + dm_docente_path, sep='|', encoding='ISO-8859-1')
dm_unidade_funcionamento = pd.read_csv(filepath_or_buffer=_2009_path + dm_unidade_funcionamento_path, sep='|', encoding='ISO-8859-1')
dm_vagas_ead = pd.read_csv(filepath_or_buffer=_2009_path + dm_vagas_ead_path, sep='|', encoding='ISO-8859-1')

print('OK.')

OK.

### Instuições de ensino superior

In [11]:
print(dm_ies.shape)
dm_ies.head()

(2314, 30)

,CO_IES,NO_IES,CO_MANTENEDORA,NO_MANTENEDORA,CO_CATEGORIA_ADMINISTRATIVA,DS_CATEGORIA_ADMINISTRATIVA,CO_ORGANIZACAO_ACADEMICA,NO_ORGANIZACAO_ACADEMICA,CO_MUNICIPIO_IES,NO_MUNICIPIO_IES,CO_UF_IES,SGL_UF_IES,NO_REGIAO_IES,IN_CAPITAL_IES,IN_ENTIDADE_BENEFICENTE,QT_TEC_TOTAL,QT_TEC_FUND_INCOMP_FEM,QT_TEC_FUND_INCOMP_MASC,QT_TEC_FUND_COMP_FEM,QT_TEC_FUND_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC
0,699,FUNDACAO UNIVERSIDADE FEDERAL DE RONDONIA,391,MINISTERIO DA EDUCACAO,1,FEDERAL,1,UNIVERSIDADE,1100205,PORTO VELHO,11,RO,Norte,1,NaN,277,5,8,15,12,61,32,39,33,40,22,7,2,1,0
1,1028,UNIVERSIDADE ESTADUAL DE MATO GROSSO DO SUL,729,SECRETARIA DE ESTADO DO MEIO AMBIENTE DAS CIDA...,2,ESTADUAL,1,UNIVERSIDADE,5003702,DOURADOS,50,MS,Centro_Oeste,0,NaN,292,0,0,1,5,14,30,86,43,67,26,13,5,1,1
2,1189,UNIVERSIDADE DO PLANALTO CATARINENSE,334,FUNDACAO DAS ESCOLAS UNIDAS DO PLANALTO CATARI...,4,PARTICULAR EM SENTIDO ESTRITO,1,UNIVERSIDADE,4209300,LAGES,42,SC,Sul,0,1.0,193,27,4,17,6,59,16,29,15,9,9,0,2,0,0
3,275,UNIVERSIDADE DO VALE DO PARAIBA,197,FUNDACAO VALEPARAIBANA DE ENSINO,5,PARTICULAR CONFESSIONAL,1,UNIVERSIDADE,3549904,SAO JOSE DO CAMPOS,35,SP,Sudeste,0,1.0,321,4,65,4,19,13,30,124,58,2,2,0,0,0,0
4,580,UNIVERSIDADE FEDERAL DE PERNAMBUCO,391,MINISTERIO DA EDUCACAO,1,FEDERAL,1,UNIVERSIDADE,2611606,RECIFE,26,PE,Nordeste,1,NaN,3389,0,21,50,83,718,785,538,295,522,181,113,48,22,13

In [12]:
dm_ies.describe()

,CO_IES,CO_MANTENEDORA,CO_CATEGORIA_ADMINISTRATIVA,CO_ORGANIZACAO_ACADEMICA,CO_MUNICIPIO_IES,CO_UF_IES,IN_CAPITAL_IES,IN_ENTIDADE_BENEFICENTE,QT_TEC_TOTAL,QT_TEC_FUND_INCOMP_FEM,QT_TEC_FUND_INCOMP_MASC,QT_TEC_FUND_COMP_FEM,QT_TEC_FUND_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC
count,2314.000000,2314.000000,2314.00000,2314.000000,2.314000e+03,2314.000000,2314.000000,2064.000000,2314.000000,2314.000000,2314.000000,2314.000000,2314.000000,2314.000000,2314.000000,2314.000000,2314.000000,2314.000000,2314.000000,2314.000000,2314.000000,2314.000000,2314.000000
mean,2198.045376,1185.799049,3.96586,2.799481,3.419088e+06,34.008643,0.362576,0.151163,152.884615,4.025497,7.624892,5.318928,7.392394,32.191443,29.843561,27.445981,17.258859,9.962403,5.430424,2.741573,2.145635,0.663354,0.839672
std,1517.113829,961.762911,0.92529,0.592852,9.196222e+05,9.196510,0.480848,0.358294,567.177639,18.722673,41.545491,18.824199,28.379444,118.861973,119.292027,117.384163,81.912172,41.443035,20.804499,15.270829,10.383438,6.900903,8.396917
min,1.000000,1.000000,1.00000,1.000000,1.100023e+06,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1045.250000,414.000000,4.00000,3.000000,2.927408e+06,29.000000,0.000000,0.000000,13.000000,0.000000,0.000000,0.000000,0.000000,3.000000,1.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1856.500000,982.500000,4.00000,3.000000,3.504503e+06,35.000000,0.000000,0.000000,31.000000,0.000000,0.000000,1.000000,1.000000,7.000000,5.000000,5.000000,2.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,3332.750000,1714.000000,4.00000,3.000000,4.106902e+06,41.000000,1.000000,0.000000,90.000000,2.000000,3.000000,4.000000,5.000000,21.000000,18.000000,15.000000,8.000000,5.000000,2.000000,1.000000,1.000000,0.000000,0.000000
max,15015.000000,14587.000000,6.00000,4.000000,5.300108e+06,53.000000,1.000000,1.000000,15350.000000,535.000000,1169.000000,371.000000,723.000000,3014.000000,3575.000000,2996.000000,2134.000000,678.000000,258.000000,440.000000,264.000000,297.000000,303.000000

### Cursos

In [13]:
print(dm_curso.shape)
dm_curso.head()

(63172, 60)

,CO_UNIDADE_FUNCIONAMENTO,CO_IES,NO_IES,CO_CATEGORIA_ADMINISTRATIVA,DS_CATEGORIA_ADMINISTRATIVA,CO_ORGANIZACAO_ACADEMICA,NO_ORGANIZACAO_ACADEMICA,CO_CURSO,NO_CURSO,CO_OCDE,NO_OCDE,CO_OCDE_AREA_GERAL,NO_AREA_GERAL,CO_OCDE_AREA_ESPECIFICA,NO_AREA_ESPECIFICA,CO_OCDE_AREA_DETALHADA,NO_AREA_DETALHADA,CO_GRAU_ACADEMICO,CO_MODALIDADE_ENSINO,CO_NIVEL_ACADEMICO,CO_MUNICIPIO_CURSO,NO_MUNICIPIO_CURSO,CO_UF_CURSO,NO_REGIAO_CURSO,IN_AJUDA_DEFICIENTE,IN_ALTO_RELEVO,IN_AUDIO,IN_BRAILLE,IN_CARACTER_AMPLIADO,IN_DISCIPLINA_LIBRAS,IN_GUIA_INTERPRETE,IN_MATERIAL_LIBRAS,IN_SINTESE_VOZ,IN_TRADUTOR_LIBRAS,IN_INTEGRAL_CURSO,IN_MATUTINO_CURSO,IN_NOTURNO_CURSO,IN_VESPERTINO_CURSO,IN_VESTIBULAR,IN_ENEM,IN_OUTRA_FORMA_SELECAO,IN_CONVENIO_PEC_G,IN_OUTRAS_FORMAS_INGRESSO,NU_CARGA_HORARIA,NU_PERC_CARGA_HOR_DISTANCIA,NU_PRAZO_INTEGRALIZACAO,QT_INSCRITOS_ANO,IN_OFERECE_DISC_DISTANCIA,IN_PARTICIPA_UAB,IN_PERMITE_CONCLUINTE,IN_UTILIZA_LABORATORIO,QT_VAGAS_INTEGRAL,QT_VAGAS_MATUTINO,QT_VAGAS_NOTURNO,QT_VAGAS_VESPERTINO,QT_MATRICULA_CURSO,QT_CONCLUINTE_CURSO,QT_INGRESSO_CURSO,QT_PROCESSO_SELETIVO,QT_PROCESSO_OUTRA_FORMA
0,78670,514,CENTRO UNIVERSITARIO DE BARRA MANSA,4,PARTICULAR EM SENTIDO ESTRITO,2,CENTRO UNIVERSITARIO,10394,ENFERMAGEM,723E01,Enfermagem,7,Saúde e bem estar social,72,Saúde,723,Enfermagem e atenção primária (assistência bás...,1.0,1,1,3300407.0,BARRA MANSA,33.0,Sudeste,1,0,1,1,1,1,0,1,1,1,1,1,1,0,1,0,1,0,1,4000,NaN,8,53.0,0.0,NaN,1,1,0,65,65,0,190,36,56,44,12
1,76698,208,UNIVERSIDADE DE RIBEIRAO PRETO,5,PARTICULAR CONFESSIONAL,1,UNIVERSIDADE,5615,DIREITO,380D01,Direito,3,"Ciências sociais, negócios e direito",38,Direito,380,Direito,1.0,1,1,3543402.0,RIBEIRAO PRETO,35.0,Sudeste,1,0,0,0,0,0,0,0,1,0,1,1,1,0,1,0,0,0,1,5070,2.0,10,741.0,1.0,NaN,1,1,0,150,150,0,800,125,208,165,43
2,76698,208,UNIVERSIDADE DE RIBEIRAO PRETO,5,PARTICULAR CONFESSIONAL,1,UNIVERSIDADE,5618,LETRAS,145F12,Formação de professor de letras,1,Educação,14,Formação de professor e ciências da educação,145,Formação de professor de matérias específicas,2.0,1,1,3543402.0,RIBEIRAO PRETO,35.0,Sudeste,1,0,0,0,0,1,0,1,1,1,1,0,1,0,1,0,0,0,1,3600,1.0,6,0.0,1.0,NaN,1,1,0,0,0,0,16,12,4,3,1
3,32121,4962,CENTRO UNIVERSITARIO DE SETE LAGOAS,4,PARTICULAR EM SENTIDO ESTRITO,2,CENTRO UNIVERSITARIO,18064,HISTORIA,145F11,Formação de professor de história,1,Educação,14,Formação de professor e ciências da educação,145,Formação de professor de matérias específicas,2.0,1,1,3167202.0,SETE LAGOAS,31.0,Sudeste,1,0,0,0,0,1,0,0,0,1,1,0,1,0,1,0,0,0,1,3000,NaN,8,0.0,0.0,NaN,1,1,0,0,0,0,35,17,0,0,0
4,76698,208,UNIVERSIDADE DE RIBEIRAO PRETO,5,PARTICULAR CONFESSIONAL,1,UNIVERSIDADE,5625,ENGENHARIA QUIMICA,524E07,Engenharia química,5,"Engenharia, produção e construção",52,Engenharia e profissões correlatas,524,Química e engenharia de processos,1.0,1,1,3543402.0,RIBEIRAO PRETO,35.0,Sudeste,1,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,4480,3.0,10,334.0,1.0,NaN,1,1,0,0,110,0,319,23,100,85,15

In [14]:
dm_curso.describe()

,CO_UNIDADE_FUNCIONAMENTO,CO_IES,CO_CATEGORIA_ADMINISTRATIVA,CO_ORGANIZACAO_ACADEMICA,CO_CURSO,CO_OCDE_AREA_GERAL,CO_OCDE_AREA_ESPECIFICA,CO_OCDE_AREA_DETALHADA,CO_GRAU_ACADEMICO,CO_MODALIDADE_ENSINO,CO_NIVEL_ACADEMICO,CO_MUNICIPIO_CURSO,CO_UF_CURSO,IN_AJUDA_DEFICIENTE,IN_ALTO_RELEVO,IN_AUDIO,IN_BRAILLE,IN_CARACTER_AMPLIADO,IN_DISCIPLINA_LIBRAS,IN_GUIA_INTERPRETE,IN_MATERIAL_LIBRAS,IN_SINTESE_VOZ,IN_TRADUTOR_LIBRAS,IN_INTEGRAL_CURSO,IN_MATUTINO_CURSO,IN_NOTURNO_CURSO,IN_VESPERTINO_CURSO,IN_VESTIBULAR,IN_ENEM,IN_OUTRA_FORMA_SELECAO,IN_CONVENIO_PEC_G,IN_OUTRAS_FORMAS_INGRESSO,NU_CARGA_HORARIA,NU_PERC_CARGA_HOR_DISTANCIA,NU_PRAZO_INTEGRALIZACAO,QT_INSCRITOS_ANO,IN_OFERECE_DISC_DISTANCIA,IN_PARTICIPA_UAB,IN_PERMITE_CONCLUINTE,IN_UTILIZA_LABORATORIO,QT_VAGAS_INTEGRAL,QT_VAGAS_MATUTINO,QT_VAGAS_NOTURNO,QT_VAGAS_VESPERTINO,QT_MATRICULA_CURSO,QT_CONCLUINTE_CURSO,QT_INGRESSO_CURSO,QT_PROCESSO_SELETIVO,QT_PROCESSO_OUTRA_FORMA
count,6.317200e+04,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,62872.000000,63172.000000,63172.000000,6.305100e+04,63051.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,4917.000000,63172.00000,28117.000000,28117.000000,35055.000000,63172.000000,63172.00000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000,63172.000000
mean,3.719406e+04,1103.679478,3.722488,1.681330,83873.796255,3.161052,35.580653,359.146014,1.991507,1.554914,1.004749,3.440840e+06,34.232431,0.724403,0.157190,0.465728,0.425457,0.518980,0.641788,0.351643,0.432502,0.352419,0.551573,0.338283,0.145143,0.338283,0.035585,0.780836,0.173542,0.243763,0.011777,0.376069,2790.500190,12.492170,6.71413,222.598677,0.174876,0.047326,0.984930,0.62572,3.238523,11.644320,33.716156,1.932708,94.755161,15.316248,32.947857,29.047901,3.899956
std,3.343219e+04,1356.345805,1.204343,0.920292,32576.777097,1.876789,18.786487,187.327992,0.876125,0.496979,0.068749,9.475438e+05,9.470792,0.446818,0.363983,0.498828,0.494416,0.499644,0.479479,0.477487,0.495427,0.477727,0.497337,0.473129,0.352248,0.473129,0.185256,0.413683,0.378718,0.429355,0.107883,0.484401,860.485676,6.977252,2.03778,998.856486,0.379868,0.212337,0.121832,0.48394,18.493933,42.825188,74.069783,13.648618,202.886673,39.970654,72.026929,63.823794,17.906042
min,1.920000e+02,1.000000,1.000000,1.000000,1.000000,1.000000,14.000000,140.000000,1.000000,1.000000,1.000000,1.100023e+06,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1600.000000,1.000000,4.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9.496000e+03,322.000000,4.000000,1.000000,68948.500000,2.000000,21.000000,210.000000,1.000000,1.000000,1.000000,2.927408e+06,29.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,2000.000000,6.000000,5.00000,35.000000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000
50%,2.450600e+04,532.000000,4.000000,1.000000,95945.500000,3.000000,34.000000,345.000000,2.000000,2.000000,1.000000,3.516200e+06,35.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,2988.000000,12.000000,7.00000,100.000000,0.000000,0.000000,1.000000,1.00000,0.000000,0.000000,0.000000,0.000000,26.000000,0.000000,6.000000,5.000000,0.000000
75%,7.714400e+04,1461.000000,4.000000,3.000000,103344.000000,4.000000,44.000000,442.000000,3.000000,2.000000,1.000000,4.117701e+06,41.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,3232.000000,20.000000,8.00000,232.000000,0.000000,0.000000,1.000000,1.00000,0.000000,0.000000,50.000000,0.000000,109.000000,16.000000,41.000000,38.000000,1.000000
max,1.046612e+06,15015.000000,6.000000,4.000000,129622.000000,8.000000,86.000000,863.000000,4.000000,2.000000,2.000000,5.300108e+06,53.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,32004.000000,20.000000,20.00000,111260.000000,1.000000,1.000000,1.000000,1.00000,1110.000000,1100.000000,1800.000000,630.000000,8586.000000,1316.000000,2879.000000,2608.000000,1054.000000

### Docente

In [7]:
print(dm_docente.shape)
dm_docente.head()

(359089, 42)

,CO_IES,NO_IES,CO_CATEGORIA_ADMINISTRATIVA,DS_CATEGORIA_ADMINISTRATIVA,CO_ORGANIZACAO_ACADEMICA,NO_ORGANIZACAO_ACADEMICA,CO_MUNICIPIO_IES,NO_MUNICIPIO_IES,CO_UF_IES,NO_REGIAO_IES,CO_VINCULO_IES_DOCENTE,CO_DOCENTE,IN_SEXO_DOCENTE,CO_PAIS_DOCENTE,CO_NACIONALIDADE_DOCENTE,NO_NACIONALIDADE_DOCENTE,CO_ESCOLARIDADE_DOCENTE,CO_COR_RACA_DOCENTE,IN_DOCENTE_DEFICIENCIA,IN_CEGUEIRA,IN_BAIXA_VISAO,IN_SURDEZ,IN_DEFICIENCIA_AUDITIVA,IN_DEFICIENCIA_FISICA,IN_SURDOCEGUEIRA,IN_DEFICIENCIA_MULTIPLA,IN_DEFICIENCIA_MENTAL,CO_SITUACAO_DOCENTE,CO_REGIME_TRABALHO,IN_ATU_EAD,IN_ATU_EXTENSAO,IN_ATU_GESTAO,IN_ATU_GRAD_PRESENCIAL,IN_ATU_POS_EAD,IN_ATU_POS_PRESENCIAL,IN_ATU_SEQUENCIAL,IN_BOLSA_PESQUISA,IN_SUBSTITUTO,NU_ANO_DOCENTE_NASC,NU_MES_DOCENTE_NASC,NU_DIA_DOCENTE_NASC,NU_IDADE_DOCENTE
0,699,FUNDACAO UNIVERSIDADE FEDERAL DE RONDONIA,1,FEDERAL,1,UNIVERSIDADE,1100205,PORTO VELHO,11,Norte,1358,92507,0,10,1,Brasileira,3,1,0,0,0,0,0,0,0,0,0,1,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1970,1,5,39
1,699,FUNDACAO UNIVERSIDADE FEDERAL DE RONDONIA,1,FEDERAL,1,UNIVERSIDADE,1100205,PORTO VELHO,11,Norte,1380,88203,1,10,1,Brasileira,5,1,0,0,0,0,0,0,0,0,0,1,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1953,5,26,56
2,699,FUNDACAO UNIVERSIDADE FEDERAL DE RONDONIA,1,FEDERAL,1,UNIVERSIDADE,1100205,PORTO VELHO,11,Norte,1391,86618,1,10,1,Brasileira,4,1,0,0,0,0,0,0,0,0,0,1,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1966,4,1,43
3,699,FUNDACAO UNIVERSIDADE FEDERAL DE RONDONIA,1,FEDERAL,1,UNIVERSIDADE,1100205,PORTO VELHO,11,Norte,13950,28342,0,10,1,Brasileira,4,6,0,0,0,0,0,0,0,0,0,1,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1969,1,13,40
4,699,FUNDACAO UNIVERSIDADE FEDERAL DE RONDONIA,1,FEDERAL,1,UNIVERSIDADE,1100205,PORTO VELHO,11,Norte,22096,53869,0,10,1,Brasileira,4,0,0,0,0,0,0,0,0,0,0,1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1981,12,7,28

In [8]:
dm_docente.describe()

,CO_IES,CO_CATEGORIA_ADMINISTRATIVA,CO_ORGANIZACAO_ACADEMICA,CO_MUNICIPIO_IES,CO_UF_IES,CO_VINCULO_IES_DOCENTE,CO_DOCENTE,IN_SEXO_DOCENTE,CO_PAIS_DOCENTE,CO_NACIONALIDADE_DOCENTE,CO_ESCOLARIDADE_DOCENTE,CO_COR_RACA_DOCENTE,IN_DOCENTE_DEFICIENCIA,IN_CEGUEIRA,IN_BAIXA_VISAO,IN_SURDEZ,IN_DEFICIENCIA_AUDITIVA,IN_DEFICIENCIA_FISICA,IN_SURDOCEGUEIRA,IN_DEFICIENCIA_MULTIPLA,IN_DEFICIENCIA_MENTAL,CO_SITUACAO_DOCENTE,CO_REGIME_TRABALHO,IN_ATU_EAD,IN_ATU_EXTENSAO,IN_ATU_GESTAO,IN_ATU_GRAD_PRESENCIAL,IN_ATU_POS_EAD,IN_ATU_POS_PRESENCIAL,IN_ATU_SEQUENCIAL,IN_BOLSA_PESQUISA,IN_SUBSTITUTO,NU_ANO_DOCENTE_NASC,NU_MES_DOCENTE_NASC,NU_DIA_DOCENTE_NASC,NU_IDADE_DOCENTE
count,359089.000000,359089.000000,359089.000000,3.590890e+05,359089.000000,359089.000000,3.590890e+05,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,340817.000000,347999.000000,347999.000000,347999.000000,347999.000000,347999.000000,347999.000000,347999.000000,347986.000000,347999.000000,359089.000000,359089.000000,359089.000000,359089.000000
mean,1148.931471,3.283860,1.848327,3.413386e+06,33.952808,425904.930716,2.377061e+10,0.449245,10.560026,1.025036,3.793466,1.905383,0.002768,0.000103,0.000613,0.000109,0.000485,0.001406,0.000017,0.000067,0.000017,1.132048,2.721158,0.019644,0.147021,0.175613,0.935195,0.003767,0.107457,0.005747,0.032774,0.055785,1965.938478,6.417442,15.385665,43.061522
std,1343.720818,1.511416,0.967259,9.093875e+05,9.090559,258662.473680,4.740245e+10,0.497418,9.119793,0.211567,0.926095,2.085793,0.052540,0.010150,0.024744,0.010421,0.022007,0.037475,0.004088,0.008175,0.004088,0.596392,1.169139,0.138773,0.354127,0.380491,0.246181,0.061262,0.309694,0.075592,0.178046,0.229506,10.879437,3.448785,8.885048,10.879437
min,1.000000,1.000000,1.000000,1.100023e+06,11.000000,761.000000,1.000000e+00,0.000000,10.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1910.000000,1.000000,1.000000,18.000000
25%,322.000000,2.000000,1.000000,2.927408e+06,29.000000,184053.000000,8.970100e+04,0.000000,10.000000,1.000000,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1958.000000,3.000000,8.000000,34.000000
50%,584.000000,4.000000,1.000000,3.506003e+06,35.000000,427042.000000,1.799670e+05,0.000000,10.000000,1.000000,4.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1967.000000,6.000000,15.000000,42.000000
75%,1542.000000,4.000000,3.000000,4.106902e+06,41.000000,672956.000000,2.867310e+05,1.000000,10.000000,1.000000,5.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1975.000000,9.000000,23.000000,51.000000
max,15015.000000,6.000000,4.000000,5.300108e+06,53.000000,866784.000000,1.189878e+11,1.000000,404.000000,3.000000,5.000000,6.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1991.000000,12.000000,31.000000,99.000000

### Aluno

In [9]:
print(dm_aluno.shape)
dm_aluno.head()

(359089, 42)

,CO_IES,NO_IES,CO_CATEGORIA_ADMINISTRATIVA,DS_CATEGORIA_ADMINISTRATIVA,CO_ORGANIZACAO_ACADEMICA,NO_ORGANIZACAO_ACADEMICA,CO_MUNICIPIO_IES,NO_MUNICIPIO_IES,CO_UF_IES,NO_REGIAO_IES,CO_VINCULO_IES_DOCENTE,CO_DOCENTE,IN_SEXO_DOCENTE,CO_PAIS_DOCENTE,CO_NACIONALIDADE_DOCENTE,NO_NACIONALIDADE_DOCENTE,CO_ESCOLARIDADE_DOCENTE,CO_COR_RACA_DOCENTE,IN_DOCENTE_DEFICIENCIA,IN_CEGUEIRA,IN_BAIXA_VISAO,IN_SURDEZ,IN_DEFICIENCIA_AUDITIVA,IN_DEFICIENCIA_FISICA,IN_SURDOCEGUEIRA,IN_DEFICIENCIA_MULTIPLA,IN_DEFICIENCIA_MENTAL,CO_SITUACAO_DOCENTE,CO_REGIME_TRABALHO,IN_ATU_EAD,IN_ATU_EXTENSAO,IN_ATU_GESTAO,IN_ATU_GRAD_PRESENCIAL,IN_ATU_POS_EAD,IN_ATU_POS_PRESENCIAL,IN_ATU_SEQUENCIAL,IN_BOLSA_PESQUISA,IN_SUBSTITUTO,NU_ANO_DOCENTE_NASC,NU_MES_DOCENTE_NASC,NU_DIA_DOCENTE_NASC,NU_IDADE_DOCENTE
0,699,FUNDACAO UNIVERSIDADE FEDERAL DE RONDONIA,1,FEDERAL,1,UNIVERSIDADE,1100205,PORTO VELHO,11,Norte,1358,92507,0,10,1,Brasileira,3,1,0,0,0,0,0,0,0,0,0,1,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1970,1,5,39
1,699,FUNDACAO UNIVERSIDADE FEDERAL DE RONDONIA,1,FEDERAL,1,UNIVERSIDADE,1100205,PORTO VELHO,11,Norte,1380,88203,1,10,1,Brasileira,5,1,0,0,0,0,0,0,0,0,0,1,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1953,5,26,56
2,699,FUNDACAO UNIVERSIDADE FEDERAL DE RONDONIA,1,FEDERAL,1,UNIVERSIDADE,1100205,PORTO VELHO,11,Norte,1391,86618,1,10,1,Brasileira,4,1,0,0,0,0,0,0,0,0,0,1,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1966,4,1,43
3,699,FUNDACAO UNIVERSIDADE FEDERAL DE RONDONIA,1,FEDERAL,1,UNIVERSIDADE,1100205,PORTO VELHO,11,Norte,13950,28342,0,10,1,Brasileira,4,6,0,0,0,0,0,0,0,0,0,1,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1969,1,13,40
4,699,FUNDACAO UNIVERSIDADE FEDERAL DE RONDONIA,1,FEDERAL,1,UNIVERSIDADE,1100205,PORTO VELHO,11,Norte,22096,53869,0,10,1,Brasileira,4,0,0,0,0,0,0,0,0,0,0,1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1981,12,7,28

In [10]:
dm_aluno.describe()

,CO_IES,CO_CATEGORIA_ADMINISTRATIVA,CO_ORGANIZACAO_ACADEMICA,CO_MUNICIPIO_IES,CO_UF_IES,CO_VINCULO_IES_DOCENTE,CO_DOCENTE,IN_SEXO_DOCENTE,CO_PAIS_DOCENTE,CO_NACIONALIDADE_DOCENTE,CO_ESCOLARIDADE_DOCENTE,CO_COR_RACA_DOCENTE,IN_DOCENTE_DEFICIENCIA,IN_CEGUEIRA,IN_BAIXA_VISAO,IN_SURDEZ,IN_DEFICIENCIA_AUDITIVA,IN_DEFICIENCIA_FISICA,IN_SURDOCEGUEIRA,IN_DEFICIENCIA_MULTIPLA,IN_DEFICIENCIA_MENTAL,CO_SITUACAO_DOCENTE,CO_REGIME_TRABALHO,IN_ATU_EAD,IN_ATU_EXTENSAO,IN_ATU_GESTAO,IN_ATU_GRAD_PRESENCIAL,IN_ATU_POS_EAD,IN_ATU_POS_PRESENCIAL,IN_ATU_SEQUENCIAL,IN_BOLSA_PESQUISA,IN_SUBSTITUTO,NU_ANO_DOCENTE_NASC,NU_MES_DOCENTE_NASC,NU_DIA_DOCENTE_NASC,NU_IDADE_DOCENTE
count,359089.000000,359089.000000,359089.000000,3.590890e+05,359089.000000,359089.000000,3.590890e+05,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,359089.000000,340817.000000,347999.000000,347999.000000,347999.000000,347999.000000,347999.000000,347999.000000,347999.000000,347986.000000,347999.000000,359089.000000,359089.000000,359089.000000,359089.000000
mean,1148.931471,3.283860,1.848327,3.413386e+06,33.952808,425904.930716,2.377061e+10,0.449245,10.560026,1.025036,3.793466,1.905383,0.002768,0.000103,0.000613,0.000109,0.000485,0.001406,0.000017,0.000067,0.000017,1.132048,2.721158,0.019644,0.147021,0.175613,0.935195,0.003767,0.107457,0.005747,0.032774,0.055785,1965.938478,6.417442,15.385665,43.061522
std,1343.720818,1.511416,0.967259,9.093875e+05,9.090559,258662.473680,4.740245e+10,0.497418,9.119793,0.211567,0.926095,2.085793,0.052540,0.010150,0.024744,0.010421,0.022007,0.037475,0.004088,0.008175,0.004088,0.596392,1.169139,0.138773,0.354127,0.380491,0.246181,0.061262,0.309694,0.075592,0.178046,0.229506,10.879437,3.448785,8.885048,10.879437
min,1.000000,1.000000,1.000000,1.100023e+06,11.000000,761.000000,1.000000e+00,0.000000,10.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1910.000000,1.000000,1.000000,18.000000
25%,322.000000,2.000000,1.000000,2.927408e+06,29.000000,184053.000000,8.970100e+04,0.000000,10.000000,1.000000,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1958.000000,3.000000,8.000000,34.000000
50%,584.000000,4.000000,1.000000,3.506003e+06,35.000000,427042.000000,1.799670e+05,0.000000,10.000000,1.000000,4.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1967.000000,6.000000,15.000000,42.000000
75%,1542.000000,4.000000,3.000000,4.106902e+06,41.000000,672956.000000,2.867310e+05,1.000000,10.000000,1.000000,5.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1975.000000,9.000000,23.000000,51.000000
max,15015.000000,6.000000,4.000000,5.300108e+06,53.000000,866784.000000,1.189878e+11,1.000000,404.000000,3.000000,5.000000,6.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1991.000000,12.000000,31.000000,99.000000

In [13]:
### Unidade de funcionamento

In [20]:
print(dm_unidade_funcionamento.shape)
dm_unidade_funcionamento.head()

(12179, 24)

,CO_UNIDADE_FUNCIONAMENTO,CO_IES,NO_IES,CO_MUNICIPIO,NO_MUNICIPIO,CO_TIPO_UNIDADE,IN_AC_BANHEIRO_ADAPTADO,IN_AC_EQUIP_ELETROMECANICO,IN_AC_MOBILIARIO_ADAPTADO,IN_AC_RAMPAS,IN_COND_ACESSIBILIDADE,IN_INST_CINEMA,IN_INST_NENHUMA,IN_INST_QUADRA,IN_INST_RESTAURANTE_UNIV,IN_INST_SERVICOS,IN_INST_TEATRO,IN_POLO_COMPARTILHADO,IN_POLO_EXTERIOR,IN_POSSUI_BIBLIOTECA,IN_POSSUI_LABORATORIO,IN_POSSUI_NEAD,IN_SUBTIPO_UNIDADE,QT_SALA_AULA
0,3994,298,UNIVERSIDADE NORTE DO PARANA,2917508.0,JACOBINA,3,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,1.0,1.0,NaN,NaN,10.0
1,3995,298,UNIVERSIDADE NORTE DO PARANA,1504208.0,MARABA,3,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,NaN,0.0,1.0,1.0,NaN,NaN,7.0
2,3996,298,UNIVERSIDADE NORTE DO PARANA,4316907.0,SANTA MARIA,3,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,1.0,1.0,NaN,NaN,5.0
3,3997,298,UNIVERSIDADE NORTE DO PARANA,3550308.0,SAO PAULO,3,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,NaN,0.0,1.0,1.0,NaN,NaN,5.0
4,3999,27,UNIVERSIDADE VALE DO RIO VERDE,3129806.0,IBIRITE,2,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,1.0,0.0,2.0,8.0

In [21]:
dm_unidade_funcionamento.describe()

,CO_UNIDADE_FUNCIONAMENTO,CO_IES,CO_MUNICIPIO,CO_TIPO_UNIDADE,IN_AC_BANHEIRO_ADAPTADO,IN_AC_EQUIP_ELETROMECANICO,IN_AC_MOBILIARIO_ADAPTADO,IN_AC_RAMPAS,IN_COND_ACESSIBILIDADE,IN_INST_CINEMA,IN_INST_NENHUMA,IN_INST_QUADRA,IN_INST_RESTAURANTE_UNIV,IN_INST_SERVICOS,IN_INST_TEATRO,IN_POLO_COMPARTILHADO,IN_POLO_EXTERIOR,IN_POSSUI_BIBLIOTECA,IN_POSSUI_LABORATORIO,IN_POSSUI_NEAD,IN_SUBTIPO_UNIDADE,QT_SALA_AULA
count,1.217900e+04,12179.000000,1.214900e+04,12179.000000,7877.000000,7877.000000,7877.000000,7877.000000,12169.000000,12169.000000,12169.000000,12169.000000,12169.000000,12169.000000,12169.000000,0.0,6453.000000,12169.000000,12169.000000,5716.00000,1723.000000,12169.000000
mean,4.302911e+04,1310.685442,3.168411e+06,2.201166,0.830265,0.245144,0.410562,0.917735,0.647301,0.014463,0.574903,0.210371,0.133290,0.106911,0.364697,NaN,0.004649,0.650998,0.691922,0.10077,1.510157,644.243405
std,3.510163e+04,1836.378597,1.088629e+06,0.904503,0.375423,0.430200,0.491967,0.274785,0.477830,0.119394,0.494378,0.407589,0.339901,0.309013,0.481365,NaN,0.068030,0.476674,0.461718,0.30105,0.511524,24079.657460
min,1.920000e+02,1.000000,1.100023e+06,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.00000,0.000000,1.000000
25%,9.826500e+03,398.000000,2.408003e+06,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.00000,1.000000,2.000000
50%,2.719900e+04,585.000000,3.205309e+06,3.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,1.000000,1.000000,0.00000,2.000000,4.000000
75%,8.114850e+04,1491.000000,4.106902e+06,3.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,NaN,0.000000,1.000000,1.000000,0.00000,2.000000,15.000000
max,1.046612e+06,15015.000000,5.300108e+06,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,1.000000,1.000000,1.000000,1.00000,2.000000,999999.000000

### Vagas Ead

In [22]:
print(dm_vagas_ead.shape)
dm_vagas_ead.head()

(849, 15)

,CO_IES,CO_CATEGORIA_ADMINISTRATIVA,DS_CATEGORIA_ADMINISTRATIVA,CO_ORGANIZACAO_ACADEMICA,NO_ORGANIZACAO_ACADEMICA,CO_MUNICIPIO_IES,NO_MUNICIPIO_IES,SGL_UF_IES,CO_CURSO_EAD,NO_CURSO_EAD,CO_GRAU_ACADEMICO,CO_NIVEL_ACADEMICO,CO_OCDE,NU_VAGAS_OFERECIDAS_EAD,QT_INSCRITOS_ANO_EAD
0,576,1,FEDERAL,1,UNIVERSIDADE,3136702,JUIZ DE FORA,MG,94681,PEDAGOGIA,2.0,1,142P01,0,0
1,576,1,FEDERAL,1,UNIVERSIDADE,3136702,JUIZ DE FORA,MG,94692,MATEMATICA EAD,2.0,1,145F18,330,431
2,576,1,FEDERAL,1,UNIVERSIDADE,3136702,JUIZ DE FORA,MG,113548,ENFERMAGEM,2.0,1,146F17,376,69
3,576,1,FEDERAL,1,UNIVERSIDADE,3136702,JUIZ DE FORA,MG,105782,ADMINISTRACAO,1.0,1,345A01,0,0
4,576,1,FEDERAL,1,UNIVERSIDADE,3136702,JUIZ DE FORA,MG,113525,QUIMICA,2.0,1,145F21,140,256

In [23]:
dm_vagas_ead.describe()

,CO_IES,CO_CATEGORIA_ADMINISTRATIVA,CO_ORGANIZACAO_ACADEMICA,CO_MUNICIPIO_IES,CO_CURSO_EAD,CO_GRAU_ACADEMICO,CO_NIVEL_ACADEMICO,NU_VAGAS_OFERECIDAS_EAD,QT_INSCRITOS_ANO_EAD
count,849.000000,849.000000,849.000000,8.490000e+02,849.000000,844.000000,849.000000,849.000000,849.000000
mean,639.651355,2.922261,1.315665,3.392121e+06,107362.512367,2.055687,1.005889,1840.641932,785.382803
std,865.950418,1.618317,0.716551,9.761370e+05,15113.103191,0.655647,0.076560,6601.485565,1849.619609
min,1.000000,1.000000,1.000000,1.100205e+06,20558.000000,1.000000,1.000000,0.000000,0.000000
25%,176.000000,1.000000,1.000000,2.927408e+06,99862.000000,2.000000,1.000000,0.000000,0.000000
50%,494.000000,4.000000,1.000000,3.304557e+06,109694.000000,2.000000,1.000000,200.000000,187.000000
75%,665.000000,4.000000,1.000000,4.205407e+06,119586.000000,2.000000,1.000000,735.000000,630.000000
max,14724.000000,6.000000,4.000000,5.300108e+06,129363.000000,4.000000,2.000000,90000.000000,19779.000000